workflows:
  nexfilesx-debug:
    name: NexFiles X Debug Build

    max_build_duration: 60

    environment:
      java: 17

    cache:
      cache_paths:
        - ~/.gradle/caches
        - ~/.gradle/wrapper

    scripts:
      - name: Grant permission
        script: |
          chmod +x gradlew

      - name: Clean project
        script: |
          ./gradlew clean

      - name: Build Debug APK
        script: |
          ./gradlew assembleDebug --stacktrace

    artifacts:
      - app/build/outputs/apk/debug/*.apk

    publishing:
      email:
        recipients:
          - prince.ar.abdur.rahman2008@gmail.com


  nexfilesx-release:
    name: NexFiles X Release Build

    max_build_duration: 60

    environment:
      java: 17

      groups:
        - keystore_credentials

    cache:
      cache_paths:
        - ~/.gradle/caches
        - ~/.gradle/wrapper

    scripts:
      - name: Grant permission
        script: |
          chmod +x gradlew

      - name: Clean project
        script: |
          ./gradlew clean

      - name: Build Release APK
        script: |
          ./gradlew assembleRelease --stacktrace

    artifacts:
      - app/build/outputs/apk/release/*.apk
      - app/build/outputs/bundle/release/*.aab

    publishing:
      email:
        recipients:
          - prince.ar.abdur.rahman2008@gmail.com
